# Generated by Django 5.1 on 2024-08-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_captions', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(upload_to='uploads/Players_images/')),
            ],
            options={
                'verbose_name_plural': 'Background Images',
            },
        ),
    ]
