# Generated by Django 5.1 on 2024-08-21 01:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_captions', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(upload_to='uploads/action_images/')),
            ],
            options={
                'verbose_name_plural': 'Background Images',
            },
        ),
        migrations.CreateModel(
            name='GameSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('home_team_scores', models.PositiveIntegerField()),
                ('away_team_scores', models.PositiveIntegerField()),
                ('highlight_moments', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_numbers', models.PositiveIntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('player_age', models.DateField(default=django.utils.timezone.now)),
                ('position', models.CharField(max_length=10)),
                ('height', models.CharField()),
                ('weight', models.CharField()),
                ('player_image', models.ImageField(upload_to='uploads/Players_images/')),
                ('player_club', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_abbreviation', models.CharField(max_length=50)),
                ('team_logo', models.ImageField(upload_to='uploads/Team_Logos/')),
                ('team_head_coach', models.CharField(max_length=50)),
                ('head_coach_photo', models.ImageField(upload_to='uploads/Coaches_Photos/')),
                ('team_assitance_coach1', models.CharField(max_length=50)),
                ('assitance_coach1_photo', models.ImageField(upload_to='uploads/Coaches_Photos/')),
                ('team_assitance_coach2', models.CharField(max_length=50)),
                ('assitance_coach2_photo', models.ImageField(upload_to='uploads/Coaches_Photos/')),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='QuarterlyScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_quarter_1', models.PositiveIntegerField()),
                ('home_team_quarter_2', models.PositiveIntegerField()),
                ('home_team_quarter_3', models.PositiveIntegerField()),
                ('home_team_quarter_4', models.PositiveIntegerField()),
                ('away_team_quarter_1', models.PositiveIntegerField()),
                ('away_team_quarter_2', models.PositiveIntegerField()),
                ('away_team_quarter_3', models.PositiveIntegerField()),
                ('away_team_quarter_4', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Ball.gameschedule')),
            ],
            options={
                'verbose_name_plural': 'Quarterly Scores',
            },
        ),
        migrations.CreateModel(
            name='PlayersStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.CharField(max_length=5)),
                ('points', models.PositiveIntegerField()),
                ('field_goal_attempts', models.PositiveIntegerField()),
                ('field_goal_made', models.PositiveIntegerField()),
                ('fg_percent', models.CharField(max_length=10)),
                ('point_3_attempts', models.PositiveIntegerField()),
                ('point_3_made', models.PositiveIntegerField()),
                ('point_3_percent', models.CharField(max_length=10)),
                ('point_2_attempts', models.PositiveIntegerField()),
                ('point_2_made', models.PositiveIntegerField()),
                ('point_2_percent', models.CharField(max_length=10)),
                ('ft_attempts', models.PositiveIntegerField()),
                ('ft_made', models.PositiveIntegerField()),
                ('ft_percent', models.CharField(max_length=10)),
                ('offensive_rebs', models.PositiveIntegerField()),
                ('defensive_rebs', models.PositiveIntegerField()),
                ('total_rebounds', models.PositiveIntegerField()),
                ('blocks', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('steals', models.PositiveIntegerField()),
                ('turnovers', models.PositiveIntegerField()),
                ('personal_fouls', models.PositiveIntegerField()),
                ('plus_minus', models.CharField(max_length=5)),
                ('efficiency', models.CharField(max_length=5)),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Ball.player')),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Ball.team')),
            ],
            options={
                'verbose_name_plural': 'Players Stats',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='B_Ball.team'),
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='B_Ball.team'),
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='B_Ball.team'),
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Ball.organizer')),
                ('teams', models.ManyToManyField(to='B_Ball.team')),
            ],
        ),
    ]
