# Generated by Django 5.1 on 2024-08-21 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_age',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_club',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Players_images/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='B_Ball.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='assitance_coach1_photo',
            field=models.ImageField(upload_to='uploads/Coaches/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='assitance_coach2_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Coaches/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='head_coach_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Coaches/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_abbreviation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_assitance_coach1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_assitance_coach2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_head_coach',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
    ]
