# Generated by Django 5.1 on 2024-08-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_abbreviation', models.CharField(max_length=50)),
                ('team_logo', models.ImageField(upload_to='uploads/Team_Logos/')),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AlterField(
            model_name='backgroundimages',
            name='image',
            field=models.ImageField(upload_to='uploads/action_images/'),
        ),
    ]
