# Generated by Django 5.1 on 2024-08-21 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0002_alter_organizer_contact_info_alter_player_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='B_Ball.team'),
        ),
    ]
