# Generated by Django 5.1 on 2024-08-21 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0003_alter_player_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='organizer',
        ),
        migrations.AddField(
            model_name='organizer',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='B_Ball.competition'),
        ),
    ]
