# Generated by Django 5.1 on 2024-08-18 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0004_playersstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playersstats',
            options={'verbose_name_plural': 'Players Stats'},
        ),
        migrations.CreateModel(
            name='QuarterlyScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_1', models.PositiveIntegerField()),
                ('quarter_2', models.PositiveIntegerField()),
                ('quarter_3', models.PositiveIntegerField()),
                ('quarter_4', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Ball.game')),
            ],
        ),
    ]
