# Generated by Django 5.1 on 2024-08-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0004_remove_competition_organizer_organizer_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='competition',
        ),
        migrations.AddField(
            model_name='competition',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='B_Ball.organizer'),
        ),
    ]
