# Generated by Django 5.1 on 2024-08-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0005_alter_playersstats_options_quarterlyscores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarterlyscores',
            name='quarter_1',
        ),
        migrations.RemoveField(
            model_name='quarterlyscores',
            name='quarter_2',
        ),
        migrations.RemoveField(
            model_name='quarterlyscores',
            name='quarter_3',
        ),
        migrations.RemoveField(
            model_name='quarterlyscores',
            name='quarter_4',
        ),
        migrations.AddField(
            model_name='quarterlyscores',
            name='away_team_quarter_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterlyscores',
            name='away_team_quarter_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterlyscores',
            name='away_team_quarter_3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterlyscores',
            name='away_team_quarter_4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterlyscores',
            name='home_team_quarter_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterlyscores',
            name='home_team_quarter_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterlyscores',
            name='home_team_quarter_3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarterlyscores',
            name='home_team_quarter_4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
