# Generated by Django 5.1 on 2024-08-22 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0005_remove_organizer_competition_competition_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimages',
            name='competition_pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_pictures', to='B_Ball.competition'),
        ),
        migrations.AddField(
            model_name='backgroundimages',
            name='player_pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_pictures', to='B_Ball.player'),
        ),
        migrations.AddField(
            model_name='backgroundimages',
            name='team_pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_pictures', to='B_Ball.team'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='organizer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Organizer_Logos/'),
        ),
    ]
