# Generated by Django 5.1 on 2024-08-19 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0006_remove_quarterlyscores_quarter_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='player_name',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='B_Ball.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='B_Ball.team'),
        ),
    ]
