# Generated by Django 5.1 on 2024-10-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0007_alter_team_assitance_coach1_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='year',
            field=models.CharField(default='2024', max_length=4),
        ),
    ]
