# Generated by Django 5.1 on 2024-10-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0008_competition_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='organizer',
        ),
        migrations.AddField(
            model_name='competition',
            name='organizer',
            field=models.ManyToManyField(related_name='competitions', to='B_Ball.organizer'),
        ),
    ]
