# Generated by Django 5.1 on 2024-10-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0009_remove_competition_organizer_competition_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='organizer',
            new_name='organizers',
        ),
    ]
