# Generated by Django 5.1 on 2024-10-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0010_rename_organizer_competition_organizers'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='competitions',
            field=models.ManyToManyField(related_name='organizers_set', to='B_Ball.competition'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='organizers',
            field=models.ManyToManyField(related_name='competitions_set', to='B_Ball.organizer'),
        ),
    ]
