# Generated by Django 5.1 on 2024-10-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0012_gameschedule_competition_game_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameschedule',
            name='away_team_scores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameschedule',
            name='home_team_scores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
