# Generated by Django 5.1 on 2024-11-13 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0013_alter_gameschedule_away_team_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='founded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_won', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('points_scored', models.IntegerField(default=0)),
                ('points_conceded', models.IntegerField(default=0)),
                ('points_scored_per_game', models.FloatField(default=0.0)),
                ('points_conceded_per_game', models.FloatField(default=0.0)),
                ('point_difference', models.FloatField(default=0.0)),
                ('expected_winning_percentage', models.FloatField(default=0.0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Ball.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Ball.team')),
            ],
        ),
    ]
