# Generated by Django 5.1 on 2024-11-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0015_rename_point_difference_standing_game_win_loss_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standing',
            name='expected_winning_percentage',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='game_win_loss_percent',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='point_difference_per_game',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='points_diff',
        ),
    ]
