# Generated by Django 5.1 on 2024-11-14 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0016_remove_standing_expected_winning_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='game_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='B_Ball.gameschedule'),
        ),
    ]
