# Generated by Django 5.1 on 2024-11-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0017_standing_game_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standing',
            name='points_conceded',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='points_scored',
        ),
    ]
