# Generated by Django 5.1 on 2024-11-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0018_remove_standing_points_conceded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standing',
            name='points_conceded_per_game',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='points_scored_per_game',
        ),
    ]
