# Generated by Django 5.1 on 2024-11-21 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0019_remove_standing_points_conceded_per_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='organizers',
        ),
        migrations.AddField(
            model_name='competition',
            name='organizers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions_set', to='B_Ball.organizer'),
        ),
    ]
