# Generated by Django 5.1 on 2024-11-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0020_remove_competition_organizers_competition_organizers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='competitions',
            field=models.ManyToManyField(blank=True, related_name='organizers_set', to='B_Ball.competition'),
        ),
    ]
