# Generated by Django 5.1 on 2024-11-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Ball', '0021_alter_organizer_competitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='competitions',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='organizers',
        ),
        migrations.AddField(
            model_name='competition',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='B_Ball.organizer'),
        ),
    ]
